export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
//
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
//
export const SET_USER = "SET_USER";
export const SET_CURRENT_STORE = "SET_CURRENT_STORE";
//
export const REGISTER_ONESIGNAL = "REGISTER_ONESIGNAL";
export const REGISTER_ONESIGNAL_SUCCESS = "REGISTER_ONESIGNAL_SUCCESS";
export const REGISTER_ONESIGNAL_ERORR = "REGISTER_ONESIGNAL_ERORR";

export const GET_MYSTORE = "GET_MYSTORE";
export const GET_MYSTORE_SUCCESS = "GET_MYSTORE_SUCCESS";
export const GET_MYSTORE_ERROR = "GET_MYSTORE_ERROR";
