const APP_CORE_SCREEN = {
  MAIN_STACK: "MAIN_STACK",
  AUTH_STACK: "AUTH_STACK",
  MODAL_STACK: "MODAL_STACK",
  MODAL_TRANSPARENT_STACK: "MODAL_TRANSPARENT_STACK",
  DEFER_SCREEN: "DEFER_SCREEN",
};
