export const LOAD_CONFIG = "LOAD_CONFIG";
export const LOAD_CONFIG_SUCCESS = "LOAD_CONFIG_SUCCESS";
export const LOAD_CONFIG_ERROR = "LOAD_CONFIG_ERROR";
//
export const LOAD_TOKEN_SHOP = "LOAD_TOKEN_SHOP";
export const LOAD_TOKEN_SHOP_SUCCESS = "LOAD_TOKEN_SHOP_SUCCESS";
export const LOAD_TOKEN_SHOP_ERROR = "LOAD_TOKEN_SHOP_ERROR";

export const LOAD_CART = "LOAD_CART";
export const LOAD_CART_SUCCESS = "LOAD_CART_SUCCESS";
export const LOAD_CART_ERROR = "LOAD_CART_ERROR";

export const LOAD_CART_TABLE = "LOAD_CART_TABLE";
export const LOAD_CART_TABLE_SUCCESS = "LOAD_CART_TABLE_SUCCESS";
export const LOAD_CART_TABLE_ERROR = "LOAD_CART_TABLE_ERROR";

export const LOAD_TABLE = "LOAD_TABLE";
export const LOAD_TABLE_SUCCESS = "LOAD_TABLE_SUCCESS";
export const LOAD_TABLE_ERROR = "LOAD_TABLE_ERROR";
//
export const SET_USER = "SET_USER";
export const SET_CURRENT_STORE = "SET_CURRENT_STORE";
//
export const REGISTER_ONESIGNAL = "REGISTER_ONESIGNAL";
export const REGISTER_ONESIGNAL_SUCCESS = "REGISTER_ONESIGNAL_SUCCESS";
export const REGISTER_ONESIGNAL_ERORR = "REGISTER_ONESIGNAL_ERORR";

export const GET_MYSTORE = "GET_MYSTORE";
export const GET_MYSTORE_SUCCESS = "GET_MYSTORE_SUCCESS";
export const GET_MYSTORE_ERROR = "GET_MYSTORE_ERROR";

export const SUBMIT_ORDER = "SUBMIT_ORDER";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const SUBMIT_ORDER_ERROR = "SUBMIT_ORDER_ERROR";

export const DELETE_BILL_ORDER = "DELETE_BILL_ORDER";
export const DELETE_BILL_ORDER_SUCCESS = "DELETE_BILL_ORDER_SUCCESS";
export const DELETE_BILL_ORDER_ERROR = "DELETE_BILL_ORDER_ERROR";

export const CHANGE_TABLE_ORDER = "CHANGE_TABLE_ORDER";
export const CHANGE_TABLE_ORDER_SUCCESS = "CHANGE_TABLE_ORDER_SUCCESS";
export const CHANGE_TABLE_ORDER_ERROR = "CHANGE_TABLE_ORDER_ERROR";

export const MERGE_TABLE_ORDER = "MERGE_TABLE_ORDER";
export const MERGE_TABLE_ORDER_SUCCESS = "MERGE_TABLE_ORDER_SUCCESS";
export const MERGE_TABLE_ORDER_ERROR = "MERGE_TABLE_ORDER_ERROR";

export const COMPLETE_ORDER = "COMPLETE_ORDER";
export const COMPLETE_ORDER_SUCCESS = "COMPLETE_ORDER_SUCCESS";
export const COMPLETE_ORDER_ERROR = "COMPLETE_ORDER_ERROR";

export const COMPLETE_TAKEAWAY_ORDER = "COMPLETE_TAKEAWAY_ORDER";
export const COMPLETE_TAKEAWAY_ORDER_SUCCESS =
  "COMPLETE_TAKEAWAY_ORDER_SUCCESS";
export const COMPLETE_TAKEAWAY_ORDER_ERROR = "COMPLETE_TAKEAWAY_ORDER_ERROR";

export const LOAD_CART_KITCHEN = "LOAD_CART_KITCHEN";
export const LOAD_CART_KITCHEN_SUCCESS = "LOAD_CART_KITCHEN_SUCCESS";
export const LOAD_CART_KITCHEN_ERROR = "LOAD_CART_KITCHEN_ERROR";

export const KITCHEN_CONFIRM_ITEM = "KITCHEN_CONFIRM_ITEM";
export const KITCHEN_CONFIRM_ITEM_SUCCESS = "KITCHEN_CONFIRM_ITEM_SUCCESS";
export const KITCHEN_CONFIRM_ITEM_ERROR = "KITCHEN_CONFIRM_ITEM_ERROR";

export const KITCHEN_CONFIRM_DELETE_ITEM = "KITCHEN_CONFIRM_DELETE_ITEM";
export const KITCHEN_CONFIRM_DELETE_ITEM_SUCCESS =
  "KITCHEN_CONFIRM_DELETE_ITEM_SUCCESS";
export const KITCHEN_CONFIRM_DELETE_ITEM_ERROR =
  "KITCHEN_CONFIRM_DELETE_ITEM_ERROR";

export const KITCHEN_CONFIRM_OK = "KITCHEN_CONFIRM_OK";
export const KITCHEN_CONFIRM_OK_SUCCESS = "KITCHEN_CONFIRM_OK_SUCCESS";
export const KITCHEN_CONFIRM_OK_ERROR = "KITCHEN_CONFIRM_OK_ERROR";

export const KITCHEN_CONFIRM_BEFORE_OK = "KITCHEN_CONFIRM_BEFORE_OK";
export const KITCHEN_CONFIRM_BEFORE_OK_SUCCESS =
  "KITCHEN_CONFIRM_BEFORE_OK_SUCCESS";
export const KITCHEN_CONFIRM_BEFORE_OK_ERROR =
  "KITCHEN_CONFIRM_BEFORE_OK_ERROR";

export const KITCHEN_TELL = "KITCHEN_TELL";
export const KITCHEN_TELL_SUCCESS = "KITCHEN_TELL_SUCCESS";
export const KITCHEN_TELL_ERROR = "KITCHEN_TELL_ERROR";

export const CASHIER_OUTLET_GENARE = "CASHIER_OUTLET_GENARE";
export const CASHIER_OUTLET_GENARE_SUCCESS = "CASHIER_OUTLET_GENARE_SUCCESS";
export const CASHIER_OUTLET_GENARE_ERROR = "CASHIER_OUTLET_GENARE_ERROR";

export const CASHIER_CONFIRM_OUTLET_GENARE = "CASHIER_CONFIRM_OUTLET_GENARE";
export const CASHIER_CONFIRM_OUTLET_GENARE_SUCCESS =
  "CASHIER_CONFIRM_OUTLET_GENARE_SUCCESS";
export const CASHIER_CONFIRM_OUTLET_GENARE_ERROR =
  "CASHIER_CONFIRM_OUTLET_GENARE_ERROR";

export const GET_MENU = "GET_MENU";
export const GET_MENU_SUCCESS = "GET_MENU_SUCCESS";
export const GET_MENU_ERROR = "GET_MENU_ERROR";

export const ALLOW_SALE = "ALLOW_SALE";
export const ALLOW_SALE_SUCCESS = "ALLOW_SALE_SUCCESS";
export const ALLOW_SALE_ERROR = "ALLOW_SALE_ERROR";

export const GET_STAFF = "GET_STAFF";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";
export const GET_STAFF_ERROR = "GET_STAFF_ERROR";

export const CALL_STAFF = "CALL_STAFF";
export const CALL_STAFF_SUCCESS = "CALL_STAFF_SUCCESS";
export const CALL_STAFF_ERROR = "CALL_STAFF_ERROR";

export const GET_INVOICE = "GET_INVOICE";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const GET_INVOICE_ERROR = "GET_INVOICE_ERROR";

export const GET_CASHIER_TODAY = "GET_CASHIER_TODAY";
export const GET_CASHIER_TODAY_SUCCESS = "GET_CASHIER_TODAY_SUCCESS";
export const GET_CASHIER_TODAY_ERROR = "GET_CASHIER_TODAY_ERROR";

// comfirm_inv;
// https://access.linkpos.top/action.php?a=table&confirm=find
//https://access.linkpos.top/action.php?a=invoice&confirm=info
