export enum cafeRoutes {
  dashBorad = "dashBorad",
  Cashier = "Cashier",
  Kitchen = "Kitchen",
  Selling = "Selling",
  Detail = "Detail",
  Cart = "Cart",
  Order = "Order",
  Bill = "Bill",
  Loader = "Loader",
  Review = "Review",
  ChangeTable = "ChangeTable",
  Takeaway = "Takeaway",
  MergeTable = "MergeTable",
  Report = "Report",
  Home = "HomeCF",
  HomeKitChen = "HomeKitChen",
  DetailConfirm = "DetailConfirm",
  Confirm = "Confirm",
  HomeCashier = "HomeCashier",
  ConfigMenu = "ConfigMenu",
  CallStaff = "CallStaff",
  DetailCashierOutlet = "DetailCashierOutlet",
  CashierToday = "CashierToday",
}
